# ================== Security =====================

initialization:
  handler: security/handler.initialization
  description: 'create CA for change refresh token period'
  tags:
    client: ${file(env.yml):${opt:stage, self:provider.stage}.CLIENT}
  timeout: 28
  events:
    - http:
        path: api/security/initialization
        method: get
        integration: lambda
        cors: true
        response:
          headers:
            Access-Control-Allow-Origin: "'*'"
            Content-Type: "'application/json'"
          template: $input.json('$')

changeRefreshTokenPeriod:
  handler: security/handler.changeRefreshTokenPeriod
  description: 'CA for change refresh token period'
  tags:
    client: ${file(env.yml):${opt:stage, self:provider.stage}.CLIENT}
  timeout: 28
  environment:
    REFRESH_TOKEN_LAMBDA_ARN: !GetAtt RefreshTokensLambdaFunction.Arn
    INVALIDATE_TOKENS_LAMBDA_ARN: !GetAtt InvalidateTokensLambdaFunction.Arn
  events:
    - http:
        path: api/security/change-refresh-token-period
        method: post
        integration: lambda
        cors: true
        response:
          headers:
            Access-Control-Allow-Origin: "'*'"
            Content-Type: "'application/json'"
          template: $input.json('$')

refreshTokens:
  handler: security/handler.refreshTokens
  description: 'refresh tokens in CA and WH every N hours'
  tags:
    client: ${file(env.yml):${opt:stage, self:provider.stage}.CLIENT}
  timeout: 28
  events:
    - http:
        path: api/security/refresh-tokens
        method: get
        integration: lambda
        cors: true
        response:
          headers:
            Access-Control-Allow-Origin: "'*'"
            Content-Type: "'application/json'"
          template: $input.json('$')

invalidateTokens:
  handler: security/handler.invalidateTokens
  description: 'invalidate tokens in CA and WH'
  tags:
    client: ${file(env.yml):${opt:stage, self:provider.stage}.CLIENT}
  timeout: 28
  events:
    - http:
        path: api/security/invalidate-tokens
        method: get
        integration: lambda
        cors: true
        response:
          headers:
            Access-Control-Allow-Origin: "'*'"
            Content-Type: "'application/json'"
          template: $input.json('$')
